# Generated by Django 5.0.3 on 2024-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='kilometres',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
