# Generated by Django 5.0.3 on 2024-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0006_alter_car_kilometres'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
